name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main
  # Adicionar suporte para execução manual
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Adicionar environment para melhor organização
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Atualizado para v4
        with:
          fetch-depth: 0 # Importante para histórico completo

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Usando LTS atual
          cache: 'npm'

      # Melhor cache de dependências
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci # Usando ci ao invés de install para maior consistência

      # Adicionando lint
      #- name: Lint check
      #  run: npm run lint || echo "No lint configured"

      - name: Build Storybook
        run: npm run build-storybook || npx storybook build

      # Validação do build
      - name: Validate build
        run: |
          if [ ! -d "storybook-static" ]; then
            echo "Storybook build failed - directory not found"
            exit 1
          fi
          if [ ! -f "storybook-static/index.html" ]; then
            echo "index.html not found in build"
            exit 1
          fi

      # Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: storybook-static
          clean: true
          clean-exclude: |
            .nojekyll